version: "2.2"
 
services:

  mqtt:
    container_name: broker
    network_mode: host
    image: eclipse-mosquitto:latest
    restart: always
# ports not used in network_mode: host
#    ports:
#      - "1883:1883"
#      - "9001:9001"

    volumes:
      - /home/tblank/code/tblank1024/rv/docker/mqtt/config:/mosquitto/config
      - /home/tblank/code/tblank1024/rv/docker/mqtt/data:/mosquitto/data
      - /home/tblank/code/tblank1024/rv/docker/mqtt/log:/mosquitto/log
      - /home/tblank/code/tblank1024/rv/docker/watcher/log:/watcher/log

  rvc2mqtt:
    build:
      context: /home/tblank/code/linuxkidd/rvc-monitor-py
      dockerfile: Dockerfile
    container_name: can
    network_mode: host
    image: rvc2mqtt:latest
    restart: always
    depends_on:
      - mqtt

  webserver:
    build:
      context: /home/tblank/code/joram/RVSecurity
      dockerfile: Dockerfile
    container_name: webserver
    network_mode: host
    image: react2:latest
    restart: always
    depends_on:
      - mqtt
      - rvc2mqtt
      - alarm

  alarm:
    build:
      context: /home/tblank/code/tblank1024/rv/alarm
      dockerfile: Dockerfile
    container_name: alarm
    network_mode: host
    restart: always
    image: alarm:latest
    privileged: true
    depends_on:
      - mqtt 

  watcher:
    build:
      context: /home/tblank/code/tblank1024/rv/watcher
      dockerfile: Dockerfile
    container_name: watcher
    network_mode: host
    restart: always
    image: watcher:latest
    privileged: false
    depends_on:
      - mqtt 
    volumes:
      - /home/tblank/code/tblank1024/rv/docker/watcherlogs:/app/watcher/watcherlogs

# bat2mqtt used to work in Buster but can't get to work in Bullseye
#
#  bat2mqtt:
#    build:
#      context: /home/tblank/code/tblank1024/rv/bat2mqtt
#      dockerfile: Dockerfile
#    container_name: battery
#    image: bat2mqtt:latest
#    network_mode: host
#    depends_on:
#      - mqtt
#    volumes:
#      #- /srv/ha_config:/config
#      #- /etc/localtime:/etc/localtime:ro
#      - /run/dbus:/run/dbus:ro
#    restart: always
#    privileged: true 


    
