services:

  mqtt:
    container_name: broker
    network_mode: host
    image: eclipse-mosquitto:latest
    restart: always
# ports not used in network_mode: host
#    ports:
#      - "1883:1883"
#      - "9001:9001"

    volumes:
      - /home/tblank/code/tblank1024/rv/docker/mqtt/config:/mosquitto/config
      - /home/tblank/code/tblank1024/rv/docker/mqtt/data:/mosquitto/data
      - /home/tblank/code/tblank1024/rv/docker/mqtt/log:/mosquitto/log
      - /home/tblank/code/tblank1024/rv/docker/watcher/log:/watcher/log

  rvc2mqtt:
    build:
      context: /home/tblank/code/linuxkidd/rvc-monitor-py
      dockerfile: Dockerfile
    container_name: can
    network_mode: host
    image: rvc2mqtt:latest
    restart: always
    depends_on:
      - mqtt

  webserver:
    environment:
      - TZ=America/Los_Angeles
      #- TZ=America/New_York
      #- TZ = America/Chicago
      #- TZ = America/Denver
      #- TZ = America/Phoenix
      #- TZ = America/Anchorage

    build:
      context: /home/tblank/code/Joram/RVSecurity
      dockerfile: Dockerfile
    container_name: webserver
    network_mode: host
    #image: react2:latest
    restart: always
    depends_on:
      - mqtt
      - rvc2mqtt
      - alarm

  alarm:
    build:
      context: /home/tblank/code/tblank1024/rv/alarm
      dockerfile: Dockerfile
    container_name: alarm
    network_mode: host
    restart: always
    image: alarm:latest
    privileged: true
    environment:
      - GPIOZERO_PIN_FACTORY=rpigpio
    devices:
      - /dev/gpiomem0:/dev/gpiomem0
      - /dev/gpiomem1:/dev/gpiomem1
      - /dev/gpiomem2:/dev/gpiomem2
      - /dev/gpiomem3:/dev/gpiomem3
      - /dev/gpiomem4:/dev/gpiomem4
      - /dev/gpiochip0:/dev/gpiochip0
      - /dev/gpiochip10:/dev/gpiochip10
      - /dev/gpiochip11:/dev/gpiochip11
      - /dev/gpiochip12:/dev/gpiochip12
      - /dev/gpiochip13:/dev/gpiochip13
      - /dev/mem:/dev/mem
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - /sys/devices/platform/soc:/sys/devices/platform/soc:ro
    depends_on:
      - mqtt 

  watcher:
    build:
      context: /home/tblank/code/tblank1024/rv/watcher
      dockerfile: Dockerfile
    container_name: watcher
    network_mode: host
    restart: always
    image: watcher:latest
    privileged: false
    depends_on:
      - mqtt 
    volumes:
      - /home/tblank/code/tblank1024/rv/docker/watcherlogs:/app/watcher/watcherlogs

  ve.direct:
    build:
      context: /home/tblank/code/tblank1024/rv/ve.direct
      dockerfile: Dockerfile
    container_name: solar
    network_mode: host
    devices:
      - /dev/ttyAMA10:/dev/ttyAMA0
    restart: always
    image: solar:latest
    privileged: false
    depends_on:
      - mqtt 

#
# bat2mqtt used to work in Buster but can't get to work in Bullseye
#
#  bat2mqtt:
#    build:
#      context: /home/tblank/code/tblank1024/rv/bat2mqtt
#      dockerfile: Dockerfile
#    container_name: battery
#    image: bat2mqtt:latest
#    network_mode: host
#    depends_on:
#      - mqtt
#    volumes:
#      #- /srv/ha_config:/config
#      #- /etc/localtime:/etc/localtime:ro
#      - /run/dbus:/run/dbus:ro
#    restart: always
#    privileged: true 


    
