version: "2.2"
 
services:

  mqtt:
    container_name: broker
    network_mode: host
    image: eclipse-mosquitto:latest
    restart: always
# ports not used in network_mode: host
#    ports:
#      - "1883:1883"
#      - "9001:9001"

    volumes:
      - /home/tblank2/code/tblank1024/rv/docker/mqtt/config:/mosquitto/config
      - /home/tblank2/code/tblank1024/rv/docker/mqtt/data:/mosquitto/data
      - /home/tblank2/code/tblank1024/rv/docker/mqtt/log:/mosquitto/log

  rvc2mqtt:
    build:
      context: /home/tblank2/code/linuxkidd/rvc-monitor-py
      dockerfile: Dockerfile
    container_name: can
    network_mode: host
    image: rvc2mqtt:latest
    restart: always
    depends_on:
      - mqtt

  webserver:
    build:
      context: /home/tblank2/code/joram/RVSecurity
      dockerfile: Dockerfile
    container_name: webserver
    network_mode: host
    image: react2:latest
    restart: always
    depends_on:
      - mqtt
      - bat2mqtt
      - rvc2mqtt
      - alarm

  alarm:
    build:
      context: /home/tblank2/code/tblank1024/rv/alarm
      dockerfile: Dockerfile
    container_name: alarm
    network_mode: host
    restart: always
    image: alarm:latest
    privileged: true
    depends_on:
      - mqtt 


  bat2mqtt:
    build:
      context: /home/tblank2/code/tblank1024/rv/bat2mqtt
      dockerfile: Dockerfile
    container_name: battery
    image: bat2mqtt:latest
    network_mode: host
    depends_on:
      - mqtt
    volumes:
      #- /srv/ha_config:/config
      #- /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: always
    privileged: true 


    
