version: "2.2"
# services:

 
services:

  mqtt:
    container_name: broker
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"

    volumes:
      - /home/pi/Code/tblank1024/rv/docker/mqtt/config:/mosquitto/config
      - /home/pi/Code/tblank1024/rv/docker/mqtt/data:/mosquitto/data
      - /home/pi/Code/tblank1024/rv/docker/mqtt/log:/mosquitto/log

  rv2mqtt:
    container_name: CAN
    network_mode: host
    image: rvc2mqtt:latest
    restart: always
    depends_on:
      - mqtt
    
