version: "2.2"
 
services:

  mqtt:
    container_name: broker
    network_mode: host
    image: eclipse-mosquitto:latest
    restart: always
# ports not used in network_mode: host
#    ports:
#      - "1883:1883"
#      - "9001:9001"

    volumes:
      - /home/pi/Code/tblank1024/rv/docker/mqtt/config:/mosquitto/config
      - /home/pi/Code/tblank1024/rv/docker/mqtt/data:/mosquitto/data
      - /home/pi/Code/tblank1024/rv/docker/mqtt/log:/mosquitto/log

  rv2mqtt:
    build:
      context: /home/pi/Code/linuxkid/rvc-monitor-py
      dockerfile: Dockerfile
    container_name: CAN
    network_mode: host
    image: rvc2mqtt:latest
    restart: always
    depends_on:
      - mqtt

  webclient:
    build:
      context: /home/pi/Code/joram/RVSecurity
      dockerfile: Dockerfile
    container_name: webclient
    network_mode: host
    image: react2:latest
    restart: always
    depends_on:
      - mqtt

#  batterypub:
#    build:
#      context: /home/pi/Code/tblank1024/rv/bat2mqtt
#      dockerfile: Dockerfile
#    container_name: bat2mqtt
#    network_mode: host
#    image: react:latest
#    restart: always
#    depends_on:
#      - mqtt


    
